### ISSUE TITLE
typed in "/wordcount", nothing shows up, does not work

### ISSUE THREAD

**Issue by OlLvERKaNe** [hkgnp/logseq-wordcount-plugin#1]
# “/wordcount” 指令没有自动补全，无法呼出
## 问题描述
插件安装途径：logseq插件市场
问题：无论在普通页面还是日记页面，无法呼出/wordcount 指令。
## 尝试解决（失败）
尝试：下载github 1.3 relase版，在logseq插件管理页面，使用“手动载入插件”功能，插件成功安装
问题：仍然，无论在普通页面还是日记页面，无法呼出/wordcount 指令。
***
不清楚是不是我自己的环境问题，其他的插件使用都没有问题。

**Comment by hkgnp** [comment]
Hi @OlLvERKaNe! Not sure why you closed the ticket, but hope your issues is resolved. 
If not, you may want to try restarting Logseq as sometimes new slash commands need a restart to be registered.

Google Translate:
嗨@OlLvERKaNe！ 不知道您为什么关闭了工单，但希望您的问题得到解决。
如果没有，您可能想尝试重新启动 Logseq，因为有时新的斜杠命令需要重新启动才能注册。

**Comment by OlLvERKaNe** [comment]
@hkgnp Thanks for your reply. After restarting Logseq, it works right now.
