### ISSUE TITLE
Russian language: word counter is not working correctly

### ISSUE THREAD

**Issue by antomal** [hkgnp/logseq-wordcount-plugin#10]
logseq-wordcount-pluginv 2.1.2

When typing in Russian letters, the word counter counts each letter as a word.

<img width="271" alt="Снимок экрана 2022-08-01 в 03 39 05" src="https://user-images.githubusercontent.com/44556749/182052664-21285b01-ea40-4138-b313-d97709c8a790.png">

**Comment by hkgnp** [comment]
Hi, please try the latest version and turn on the below function in the plugin settings.

<img width="678" alt="Screenshot 2022-11-07 at 11 13 54 AM" src="https://user-images.githubusercontent.com/47936793/200218902-ad1d1761-ff91-4cc8-b4b0-d1ae2520d5db.png">

**Comment by antomal** [comment]
Great! Thank you!
