### ISSUE TITLE
option to not count tags as words

### ISSUE THREAD

**Issue by aspgh** [hkgnp/logseq-wordcount-plugin#11]
Hello. If it is not too difficult to implement, I would like to request for an additional option for the plugin to ignore the tags (#tags) at the end of the blocks, and not count them as words in the text that we're writing. [[Links]] would be a different case, since they are actually part of the 'output' text / final product. Well, not all users employ tags and links in this way, but at least it would be good to have this option available, just in case.
Thanks!

**Comment by hkgnp** [comment]
I think the issue is sometimes they are being used not as tags. Hence, it may be difficult to identify what is really a tag or not.

Sorry!
