### ISSUE TITLE
Feature request: Tweet character target

### ISSUE THREAD

**Issue by Yanivro** [hkgnp/logseq-wordcount-plugin#12]
Hi! Amazing plugin, I love it. Thank you for creating it.

I am curious if you are willing to add a character count target? would be very useful for writing tweets since they have a target of 280 Characters. What do you think?

Thank you again!

**Comment by hkgnp** [comment]
Hi!
The logseq-tweet-plugin (https://github.com/hkgnp/logseq-tweet-plugin) has
that.

**Comment by hkgnp** [comment]
Also, you can update to v2.2.1 and try Tweet character counts using `/Tweet target`. However, works only for languages that use the alphabets.
