### ISSUE TITLE
letters count as words 

### ISSUE THREAD

**Issue by PSEUDO-SAPPHO** [hkgnp/logseq-wordcount-plugin#14]
plugin doesn't work well with Arabic and Persian text; it counts letters as words.

**Comment by hkgnp** [comment]
Can you take a screenshot of your settings page?Regards,ben On 22 Jan 2023, at 10:53 PM, PSEUDO-SAPPHO ***@***.***> wrote:﻿
plugin doesn't work well with Arabic and Persian text; it counts letters as words.

**Comment by PSEUDO-SAPPHO** [comment]
![image](https://user-images.githubusercontent.com/82666844/214129894-673af8da-4b02-4fdc-a02d-2a682b59829d.png)
 they are two words in " کلمه نخسین"‌.

**Comment by hkgnp** [comment]
Try turning on this option in the plugin settings.

<img width="696" alt="Screenshot 2023-01-25 at 10 51 41 AM" src="https://user-images.githubusercontent.com/47936793/214470198-4ad4b8ca-1c57-4eec-a416-bb14bc49e038.png">
