### ISSUE TITLE
FR: Word count the current block without indentation

### ISSUE THREAD

**Issue by AvijeetPrasad** [hkgnp/logseq-wordcount-plugin#15]
Hi, 
Currently, we need to indent a block under the renderer to get its word count. It would be great if the renderer can be placed on the same block and still get the word count. This will prevent us from having too many indentations and quickly remove the renders from the text later on without changing the overall structure.

**Comment by aifreedom** [comment]
+1

Can we have another command that counts words in all sibling blocks?

**Comment by bradmont** [comment]
Sibling blocks would be excellent, this would be most useful for longform writing, where I'd want a word count for a whole page.

**Comment by hkgnp** [comment]
Ok, am working on it!

**Comment by hkgnp** [comment]
This is available in v2.4.0. Activated using `/wordcount - page`. It's a little bit less responsive than nested blocks as it is using a different plugin api.

**Comment by hkgnp** [comment]
![my](https://user-images.githubusercontent.com/47936793/221086104-bf2378ea-9dca-486d-a831-459af7c999e6.gif)

In v2.4.2.
