### ISSUE TITLE
Word count - page is annoying

### ISSUE THREAD

**Issue by hezhizhen** [hkgnp/logseq-wordcount-plugin#16]
It keeps updating itself after I delete it

**Comment by hkgnp** [comment]
Do you have a screenshot? I don't understand the issue.

**Comment by hezhizhen** [comment]
https://user-images.githubusercontent.com/7611700/224320429-10cdaaf7-9bdb-4ad9-96ee-361c88d6998d.mp4

**Comment by hezhizhen** [comment]
As the video shows, it's really difficult to delete it.

- Logseq: 0.8.18
- macOS: 13.2.1

**Comment by hkgnp** [comment]
Should be fixed in the latest version.

**Comment by hezhizhen** [comment]
> Should be fixed in the latest version.

Thanks.

**Comment by hkgnp** [comment]
Sorry for the late response. Been busy at work. Can you try v2.4.4. Caveat is the count needs to be in the first block (like how you are doing in your example).

**Comment by hezhizhen** [comment]
https://user-images.githubusercontent.com/7611700/228141022-e470e21c-f94d-41b3-bde3-b231bb510237.mp4

I'm using 2.4.7, and it seems all fine. Just one little question: why does the second word counter not work?

**Comment by hezhizhen** [comment]
Thanks a lot!
