### ISSUE TITLE
FR: a "wordcount - page (main view)" renderer that we can put in [[Contents]] that counts for the page in the main view

### ISSUE THREAD

**Issue by lef-est** [hkgnp/logseq-wordcount-plugin#18]
then it can be used like a widget like sethyuan's toc plugin, and there'll be no need to invoke the "wordcount - page" command for every page :D

Besides: i think "writing session target" needs to be added to the Readme. When we type `/word` to look for commands this plugin offers, that option wouldn't appear, so I doubt many users know this amazing function!

**Comment by hkgnp** [comment]
If you go into plugin settings, you can turn on the "Toolbar Wordcount" setting and the number of words will be displayed in the toolbar.

Noted on updating the README. I've lots of plugins that need their READMEs to be updated!

**Comment by lef-est** [comment]
> If you go into plugin settings, you can turn on the "Toolbar Wordcount" setting and the number of words will be displayed in the toolbar.
> 
> Noted on updating the README. I've lots of plugins that need their READMEs to be updated!

oh I posted this because I already tried that setting and nothing appeared on my toolbar when toggled. maybe a restart is what'll get it to work, I'll test again later 😂

**Comment by lef-est** [comment]
The toolbar feature is working now, thanks!
