### ISSUE TITLE
Enhancement request: allow for empty blocks

### ISSUE THREAD

**Issue by kerim** [hkgnp/logseq-wordcount-plugin#19]
I love that the wordcount plugin can keep a running tally of all the words in nested child blocks, however, when there is an empty block it seems to choke and says "NaN" instead of giving the word count. I'd like it to ignore empty blocks and keep the display of the current word count even if there are one or more empty blocks.

**Comment by hkgnp** [comment]
Should be fixed in the latest version.

**Comment by kerim** [comment]
It is. Thanks!
