### ISSUE TITLE
No word count text 

### ISSUE THREAD

**Issue by richd67** [hkgnp/logseq-wordcount-plugin#2]
Just tried this for the first time and the {{renderer :wordcount_rzcwplra}} simply disappears with no word count?

**Comment by hkgnp** [comment]
@richd67 Hi! It used to only work on pages (journal or normal).

But I suddenly thought of an idea, and now it works on the home page too. Just update from the marketplace!

**Comment by richd67** [comment]
Yes update to 1.4 has fixed it, Thanks

**Comment by hkgnp** [comment]
Cool! Thanks for trying the plugin!
