### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by kerim** [hkgnp/logseq-wordcount-plugin#20]
Not having any issues, but I saw this in the developer console and thought you should know.

<img width="553" alt="Screenshot 2023-04-28 at 6 26 20 AM" src="https://user-images.githubusercontent.com/59976/235004837-3160d30d-6921-4d43-be74-d2140da8734e.png">

(This is happening all the time, even when I'm not working on a page with wordcount enabled.)

**Comment by hkgnp** [comment]
Should be fixed in latest version.

**Comment by kerim** [comment]
I'm afraid there are still some errors.
<img width="552" alt="Screenshot 2023-05-01 at 10 01 16 AM" src="https://user-images.githubusercontent.com/59976/235390211-76c3a6ae-543e-4e00-bfaf-0e8f1ce6448b.png">

**Comment by hkgnp** [comment]
Apologies, please see the latest version.
