### ISSUE TITLE
How about let it works on page properties like another plugin TODO master?

### ISSUE THREAD

**Issue by hh23485** [hkgnp/logseq-wordcount-plugin#3]
How about let word count works on page properties like another plugin [TODO master](https://github.com/pengx17/logseq-plugin-todo-master)?

for example

![image](https://user-images.githubusercontent.com/14577931/146643365-8de82174-1aa2-44d4-858f-a576d9acb177.png)

Then, it will count all words in this page.

**Comment by hkgnp** [comment]
Thanks for the suggestion!

Once the plugin API has been updated, I'll be implementing a page wide count! 

Stay tuned!
