### ISSUE TITLE
希望能在界面上做一个按钮，统计该页面的字数

### ISSUE THREAD

**Issue by hdg8087** [hkgnp/logseq-wordcount-plugin#6]
目前只能统计某个节点及其子节点的数字，功能稍弱。

**Comment by hkgnp** [comment]
Sorry I am not sure I understand. What is the bug?

**Comment by hdg8087** [comment]
very good, no bug, just need a command button like these
![1645788334(1)](https://user-images.githubusercontent.com/71086865/155707466-08d41714-44d4-491f-acb0-0ae7a5b35ef0.png)

**Comment by hkgnp** [comment]
Oh I see!
And what will the command button do? Calculate all words on the page?

**Comment by hdg8087** [comment]
yes, thank you!

**Comment by hkgnp** [comment]
> If so, this [plugin](https://github.com/pengx17/logseq-plugin-random-tools) maybe suitable?

Can try this: https://github.com/pengx17/logseq-plugin-random-tools

**Comment by hdg8087** [comment]
yes, so good. thank you very much
