### ISSUE TITLE
Feature request: Writing Session Target

### ISSUE THREAD

**Issue by nomad101** [hkgnp/logseq-wordcount-plugin#7]
Hi, thanks for putting together this plugin. I see it as essential for any writer.

I'm aware of the effort involved. Would you consider extending the features of the plugin. That is, to enable the user to set a target for a writing session. For example, say you wanted to write 500 words, the user would input that in, and the display could be how many words currently written (and possibly also displayed as %). 

Additionally, probably more tricky(?) any comments would be excluded from the word count. 

Thanks for reading

**Comment by hkgnp** [comment]
what are comments?

**Comment by nomad101** [comment]
I'll give an example.

**Here is some text I'm writing but I'm not sure about the object of the sentence %%fix this%% and what I want to actually say. Now if I could just do what I want to, and not worry about it.
%%look up ref%%

It take  a great deal of time to write effectively.**

The text between the %% ...%% are comments. And ideally, shouldn't be counted in a word count. 

Hope that's clear.

**Comment by hkgnp** [comment]
Oh is %% a Logseq syntax or just your own personal one?

**Comment by nomad101** [comment]
Apologies. For indicating the use of %% ... %%, I was getting mixed up with Obsidian.

I'm still new to Logseq, and don't think it currently has an elegant, minimal method of making in-line comments?

**Comment by hkgnp** [comment]
Can give v2.1.0 a try. Choose the option `Writing session target`.

The default target number of words is 500. You can change it to any number you like.
`{{renderer :wordcount_chonikxm, 500}}` to `{{renderer :wordcount_chonikxm, 1000}}`
