### ISSUE TITLE
long floating number in the writing target 

### ISSUE THREAD

**Issue by jarodise** [hkgnp/logseq-wordcount-plugin#8]
Really love this new feature, but I noticed as I write under the "writing target", the percentage number sometimes is shown as very long floating numbers, see the screenshot below, 

![CleanShot 2022-06-23 at 18 06 46@2x](https://user-images.githubusercontent.com/15899808/175333038-2995a19d-f623-4577-aa22-32109f3d9e9e.png)

I think using integers would be fine for the percentage, just a suggestion.

**Comment by hkgnp** [comment]
Please see v2.1.2. Thanks.
