### ISSUE TITLE
it doesn't work well

### ISSUE THREAD

**Issue by StacyHe** [hkgnp/logseq-wordcount-plugin#9]
When I type the /wordcount in Logsql，it always becomes the journal symbol

**Comment by hkgnp** [comment]
Could you provide a screenshot please?

**Comment by StacyHe** [comment]
![c2f3e6c3ab78edb997dd224380ea26d](https://user-images.githubusercontent.com/78797029/179910964-c774a9a8-2635-45ac-9a77-891f2d816b7c.png)

**Comment by hkgnp** [comment]
I am so sorry, I am not sure what you mean by the journal symbol?
